site_name: Documentação Software Biblioteca
theme: readthedocs

nav:
  - Página inicial: index.md
  - Diagramas: diagramas.md

markdown_extensions:
  - attr_list
  - footnotes
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

plugins:
  - search