name: Transfere páginas HTML para o GitHub Pages
on:
  push:
    branches:
      - main
jobs:
  docs:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'  # permite ler o conteúdo do repositório (necessário para clonar o código)
      pages: 'write'  # permite escrever no GitHub Pages
      id-token: 'write'  # permite autenticação OIDC (usada internamente pelo GitHub Actions para autorizar o deploy
    steps:
      - name: Clona repositório no servidor remoto do GitHub
        uses: actions/checkout@v5

      - name: Configura o GitHub Pages
        uses: actions/configure-pages@v3

      - name: Envia dados para o GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'website/'

      - name: Publica páginas HTML no GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}